name: event-handler

on: [push]

jobs:
  test:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.20
    - name: Install Redis
      run: sudo apt-get install redis-server
    - name: Start Redis Service
      run: sudo service redis-server start
    - name: Run unit tests
      run: go test -cover ./...
